name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        use_fmtlib: [ON, OFF]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        cmake --version
    - name: Set up CMake
      if: runner.os != 'Windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        cmake --version

    - name: Configure CMake
      run: cmake -B build -DRTLOG_USE_FMTLIB=${{ matrix.use_fmtlib }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DRTLOG_FULL_WARNINGS=ON -DRTLOG_BUILD_TESTS=ON -DRTLOG_BUILD_EXAMPLES=ON

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }} -j 2

    - name: Test
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }} --timeout 10
